[package]
name = "tower-grpc-build"
version = "0.1.0"
authors = ["Carl Lerche <me@carllerche.com>"]

[dependencies]
codegen = { git = "https://github.com/hawkw/codegen", branch = "eliza/get-or-create"}
prost-build = "0.2"

